export default {
	
  "login": "djzg",
  "id": 12217840,
  "node_id": "MDQ6VXNlcjEyMjE3ODQw",
  "avatar_url": "https://avatars.githubusercontent.com/u/12217840?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/djzg",
  "html_url": "https://github.com/djzg",
  "followers_url": "https://api.github.com/users/djzg/followers",
  "following_url": "https://api.github.com/users/djzg/following{/other_user}",
  "gists_url": "https://api.github.com/users/djzg/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/djzg/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/djzg/subscriptions",
  "organizations_url": "https://api.github.com/users/djzg/orgs",
  "repos_url": "https://api.github.com/users/djzg/repos",
  "events_url": "https://api.github.com/users/djzg/events{/privacy}",
  "received_events_url": "https://api.github.com/users/djzg/received_events",
  "type": "User",
  "site_admin": false,
  "name": "DJZG",
  "company": null,
  "blog": "",
  "location": "Zagreb, Croatia",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 18,
  "public_gists": 0,
  "followers": 0,
  "following": 2,
  "created_at": "2015-05-03T07:59:08Z",
  "updated_at": "2021-04-17T20:10:29Z"
};
